# Generated by Django 6.0.5 on 2026-05-31 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examfee',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='examfee',
            name='trade',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply this fee to ALL trades at this chamber for the selected part. A trade-specific entry always takes precedence over an all-trades entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_fees', to='chambers.trade'),
        ),
    ]
