# Generated by Django 6.0.5 on 2026-05-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_examfee_unique_together_alter_examfee_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='examfee',
            name='fee_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Optional upper bound for a range, e.g. enter 600 here and 2000 in fee_max to display '600,00 bis 2.000,00 €'. Leave blank for a single value.", max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='examfee',
            name='fee',
            field=models.DecimalField(decimal_places=2, help_text='Fee amount (or lower bound of a range).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='examfee',
            name='fee_qualifier',
            field=models.CharField(blank=True, default='', help_text="Optional qualifier displayed before the fee, e.g. 'bis zu' for maximum fees (as in HWK Koblenz Gebührenverzeichnis). Leave blank for exact amounts. Not used when fee_max is set (the range itself communicates variability).", max_length=20),
        ),
    ]
