# Generated by Django 6.0.5 on 2026-06-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_examfee_fee_max_alter_examfee_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffer',
            name='availability',
            field=models.CharField(choices=[('available', 'Freie Plätze'), ('few_spots', 'Wenige Plätze'), ('full', 'Ausgebucht'), ('waitlist', 'Warteliste'), ('unknown', 'Unbekannt')], default='unknown', max_length=20),
        ),
    ]
